services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./main_py:/app/main_py
      - ./pattern-data:/app/pattern-data
    env_file:
      - ./secrets/.env
    secrets:
      - postgres_password
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/app/httpcheck", "http://localhost:8080/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:18.3-alpine3.23
    environment:
      - POSTGRES_DB=AAO_DB
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    name: postgres_db

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
