CREATE TABLE IF NOT EXISTS UserCredentials (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    password_hash VARCHAR NOT NULL,
    salt VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE
);